
import { BookOpen } from "lucide-react";
import type { StudentCourse } from "../types/student-course.types";

export const coursesData: StudentCourse[] = [
  {
    id: "course-1",
    name: "Matemáticas",
    teacher: { id: 1, firstName: "María", lastName: "García", email: "maria.garcia@example.com", username: "maria.garcia", role: "TEACHER", isActive: true },
    credits: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. María García",
    schedule: "Lun, Mie - 8:00 AM",
    nextClass: "Lunes 14 Oct - Ecuaciones Cuadráticas",
    materials: [],
    videos: [],
    students: [],
    progress: 75,
    color: "blue",
    icon: BookOpen,
  },
  {
    id: "course-2",
    name: "Comunicación",
    teacher: { id: 2, firstName: "Roberto", lastName: "Rodríguez", email: "roberto.rodriguez@example.com", username: "roberto.rodriguez", role: "TEACHER", isActive: true },
    credits: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. Roberto Rodríguez",
    schedule: "Mar, Jue - 10:00 AM",
    nextClass: "Martes 15 Oct - Literatura Contemporánea",
    materials: [],
    videos: [],
    students: [],
    progress: 82,
    color: "green",
    icon: BookOpen,
  },
  {
    id: "course-3",
    name: "Ciencias Sociales",
    teacher: { id: 3, firstName: "Ana", lastName: "Silva", email: "ana.silva@example.com", username: "ana.silva", role: "TEACHER", isActive: true },
    credits: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. Ana Silva",
    schedule: "Lun, Mie - 2:00 PM",
    nextClass: "Lunes 14 Oct - Historia del Perú Republicano",
    materials: [],
    videos: [],
    students: [],
    progress: 68,
    color: "purple",
    icon: BookOpen,
  },
  {
    id: "course-4",
    name: "Ciencia y Tecnología",
    teacher: { id: 4, firstName: "Carlos", lastName: "López", email: "carlos.lopez@example.com", username: "carlos.lopez", role: "TEACHER", isActive: true },
    credits: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. Carlos López",
    schedule: "Mar, Vie - 11:00 AM",
    nextClass: "Martes 15 Oct - Física Cuántica",
    materials: [],
    videos: [],
    students: [],
    progress: 90,
    color: "orange",
    icon: BookOpen,
  },
  {
    id: "course-5",
    name: "Inglés",
    teacher: { id: 5, firstName: "Jennifer", lastName: "Smith", email: "jennifer.smith@example.com", username: "jennifer.smith", role: "TEACHER", isActive: true },
    credits: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. Jennifer Smith",
    schedule: "Lun, Jue - 9:00 AM",
    nextClass: "Lunes 14 Oct - Advanced Grammar",
    materials: [],
    videos: [],
    students: [],
    progress: 85,
    color: "blue",
    icon: BookOpen,
  },
  {
    id: "course-6",
    name: "Educación Física",
    teacher: { id: 6, firstName: "Diego", lastName: "Martínez", email: "diego.martinez@example.com", username: "diego.martinez", role: "TEACHER", isActive: true },
    credits: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. Diego Martínez",
    schedule: "Mié, Vie - 3:00 PM",
    nextClass: "Miércoles 16 Oct - Deportes de Equipo",
    materials: [],
    videos: [],
    students: [],
    progress: 95,
    color: "green",
    icon: BookOpen,
  },
  {
    id: "course-7",
    name: "Arte y Cultura",
    teacher: { id: 7, firstName: "Laura", lastName: "Castillo", email: "laura.castillo@example.com", username: "laura.castillo", role: "TEACHER", isActive: true },
    credits: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. Laura Castillo",
    schedule: "Jue - 1:00 PM",
    nextClass: "Jueves 17 Oct - Historia del Arte Peruano",
    materials: [],
    videos: [],
    students: [],
    progress: 72,
    color: "purple",
    icon: BookOpen,
  },
  {
    id: "course-8",
    name: "Religión",
    teacher: { id: 8, firstName: "Pedro", lastName: "Ramírez", email: "pedro.ramirez@example.com", username: "pedro.ramirez", role: "TEACHER", isActive: true },
    credits: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    professor: "Prof. Pedro Ramírez",
    schedule: "Mar - 1:00 PM",
    nextClass: "Martes 15 Oct - Valores Ignacianos",
    materials: [],
    videos: [],
    students: [],
    progress: 88,
    color: "orange",
    icon: BookOpen,
  },
];
