
import type { StudentCourse } from "../types/student-course.types";

export const coursesData: StudentCourse[] = [
  {
    id: "course-1",
    name: "Matemáticas",
    professor: "Prof. María García",
    schedule: "Lun, Mie - 8:00 AM",
    nextClass: "Lunes 14 Oct - Ecuaciones Cuadráticas",
    materials: 12,
    videos: 8,
    students: 28,
    progress: 75,
    color: "blue",
  },
  {
    id: "course-2",
    name: "Comunicación",
    professor: "Prof. Roberto Rodríguez",
    schedule: "Mar, Jue - 10:00 AM",
    nextClass: "Martes 15 Oct - Literatura Contemporánea",
    materials: 15,
    videos: 6,
    students: 28,
    progress: 82,
    color: "green",
  },
  {
    id: "course-3",
    name: "Ciencias Sociales",
    professor: "Prof. Ana Silva",
    schedule: "Lun, Mie - 2:00 PM",
    nextClass: "Lunes 14 Oct - Historia del Perú Republicano",
    materials: 10,
    videos: 5,
    students: 28,
    progress: 68,
    color: "purple",
  },
  {
    id: "course-4",
    name: "Ciencia y Tecnología",
    professor: "Prof. Carlos López",
    schedule: "Mar, Vie - 11:00 AM",
    nextClass: "Martes 15 Oct - Física Cuántica",
    materials: 14,
    videos: 10,
    students: 28,
    progress: 90,
    color: "orange",
  },
  {
    id: "course-5",
    name: "Inglés",
    professor: "Prof. Jennifer Smith",
    schedule: "Lun, Jue - 9:00 AM",
    nextClass: "Lunes 14 Oct - Advanced Grammar",
    materials: 11,
    videos: 7,
    students: 28,
    progress: 85,
    color: "blue",
  },
  {
    id: "course-6",
    name: "Educación Física",
    professor: "Prof. Diego Martínez",
    schedule: "Mié, Vie - 3:00 PM",
    nextClass: "Miércoles 16 Oct - Deportes de Equipo",
    materials: 5,
    videos: 3,
    students: 28,
    progress: 95,
    color: "green",
  },
  {
    id: "course-7",
    name: "Arte y Cultura",
    professor: "Prof. Laura Castillo",
    schedule: "Jue - 1:00 PM",
    nextClass: "Jueves 17 Oct - Historia del Arte Peruano",
    materials: 8,
    videos: 4,
    students: 28,
    progress: 72,
    color: "purple",
  },
  {
    id: "course-8",
    name: "Religión",
    professor: "Prof. Pedro Ramírez",
    schedule: "Mar - 1:00 PM",
    nextClass: "Martes 15 Oct - Valores Ignacianos",
    materials: 6,
    videos: 2,
    students: 28,
    progress: 88,
    color: "orange",
  },
];
