import { TrendingUp, Book, FileText, Users, BookOpen } from "lucide-react";
import type { Stats } from "@/shared/types/stats.types";
import type { StudentCourse } from "../types/student-course.types";
import type { Event } from "@/shared/types/event.types";

export const statsData: Stats[] = [
  {
    id: "1",
    value: "95.0",
    label: "Promedio General",
    subtitle: "+2.5 este mes",
    icon: TrendingUp,
    color: "green",
  },
  {
    id: "2",
    value: "8",
    label: "Cursos Activos",
    subtitle: "Ciclo I - 2025",
    icon: Book,
    color: "blue",
  },
  {
    id: "3",
    value: "5",
    label: "Tareas Pendientes",
    subtitle: "2 para esta semana",
    icon: FileText,
    color: "orange",
  },
  {
    id: "4",
    value: "98%",
    label: "Asistencia",
    subtitle: "Excelente registro",
    icon: Users,
    color: "purple",
  },
];

export const coursesData: StudentCourse[] = [
  {
    id: "1",
    name: "Matemáticas",
    professor: "Prof. García",
    progress: 75,
    color: "blue",
    icon: BookOpen,
    teacher: { id: 1, firstName: "María", lastName: "García", email: "maria.garcia@example.com", username: "maria.garcia", role: "TEACHER", isActive: true },
    credits: 4,
    students: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    schedule: "Lunes, Miércoles, Viernes 08:00 - 09:30 AM",
    nextClass: "Miércoles 08:00 AM",
    materials: [],
    videos: [],
  },
  {
    id: "2",
    name: "Comunicación",
    professor: "Prof. Rodríguez",
    progress: 82,
    color: "green",
    icon: BookOpen,
    teacher: { id: 2, firstName: "Roberto", lastName: "Rodríguez", email: "roberto.rodriguez@example.com", username: "roberto.rodriguez", role: "TEACHER", isActive: true },
    credits: 3,
    students: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    schedule: "Martes, Jueves 10:00 - 11:30 AM",
    nextClass: "Jueves 10:00 AM",
    materials: [],
    videos: [],
  },
  {
    id: "3",
    name: "Ciencias Sociales",
    professor: "Prof. Silva",
    progress: 68,
    color: "purple",
    icon: BookOpen,
    teacher: { id: 3, firstName: "Ana", lastName: "Silva", email: "ana.silva@example.com", username: "ana.silva", role: "TEACHER", isActive: true },
    credits: 3,
    students: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    schedule: "Lunes, Miércoles 02:00 - 03:30 PM",
    nextClass: "Lunes 02:00 PM",
    materials: [],
    videos: [],
  },
  {
    id: "4",
    name: "Ciencia y Tecnología",
    professor: "Prof. López",
    progress: 90,
    color: "orange",
    icon: BookOpen,
    teacher: { id: 4, firstName: "Carlos", lastName: "López", email: "carlos.lopez@example.com", username: "carlos.lopez", role: "TEACHER", isActive: true },
    credits: 4,
    students: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    schedule: "Martes, Viernes 11:00 - 12:30 PM",
    nextClass: "Martes 11:00 AM",
    materials: [],
    videos: [],
  },
];

export const eventsData: Event[] = [
  {
    id: "1",
    day: "15",
    month: "Oct",
    title: "Examen de Matemáticas",
    time: "08:00 AM",
    color: "red",
  },
  {
    id: "2",
    day: "18",
    month: "Oct",
    title: "Entrega de Proyecto",
    subtitle: "Historia del Perú",
    color: "blue",
  },
  {
    id: "3",
    day: "20",
    month: "Oct",
    title: "Feria de Ciencias",
    subtitle: "Todo el día",
    color: "green",
  },
];

export const cycleProgressData = {
  cycleName: "Ciclo I",
  progress: 65,
  startDate: "01 de Marzo",
  endDate: "31 de Julio",
  remainingDays: 52,
};